### ISSUE TITLE
Heartbeat does not respond to timeout while waiting for a response from the server

### ISSUE THREAD

**Issue by IstominP** [apache/mina-sshd#268]
If heartbeat is waiting for a response from the server and the response did not come within the allotted time, then we must kill the session because the server is not responding, in which case the lack of response to waiting for a response in `org.apache.sshd.client.session.ClientConnectionService#sendHeartBeat` looks like wrong behavior.

Should we do something like
`
if (!replyReceived.await(toWait, TimeUnit.MILLISECONDS)) {  
  throw new TimeoutException("No response from server");  
}
`
when waiting response on heartbeat request

![timeout](https://user-images.githubusercontent.com/10018643/201108463-95e39c8b-e777-43ee-bd28-9c76c1a4ddf5.png)

Am I understanding heartbeat logic correctly?

**Comment by Brikman** [comment]
@tomaswolf can you explain in more detail please?

Did I understand correctly that you are proposing to roll back and generally refuse to wait for a response to a heartbeat?

Are there any disadvantages or fundamental errors in the solution proposed by @robober? Is it correct in principle to wait response to every heartbeat?

**Comment by tomaswolf** [comment]
> proposing to roll back

Yes.

> and generally refuse to wait for a response to a heartbeat?

No. Seems to me that rolling back would use the synchronous `session.request()` method (again), which does wait for the response and which does throw a `SocketTimeoutException` if a timeout occurs. If that is correct, then rolling back would be the preferred solution since it simplifies the code quite a bit.

> Are there any disadvantages or fundamental errors in the solution proposed by @robober?

No. But looking back at this code, I don't see anymore why I even changed it. Using the asynchronous global request but then waiting on the latch is still blocking of course. But heartbeats are sent from separate threads anyway, so this doesn't block an I/O thread.

**Comment by Brikman** [comment]
Thank you for explanation.

In this case, we will use our modified heartbeat for a while, waiting for fix in library.
