### ISSUE TITLE
How do I force the use of "RSA key" to connect to the remote side?

### ISSUE THREAD

**Issue by jiahui-qin** [apache/mina-sshd#317]
### Version

2.7.0

### Bug description

I notice sometimes sshd use "rsa key" connect remote, log like this 
```
"Server at /192.168.218.182:830 presented unverified RSA key: SHA256:3lpuMiEyQ192HpfOAwjv+jhmliKfrG7w2Yl8x4bpfog"
```
and sometimes use "ec key"
```
Server at /192.168.218.182:830 presented unverified EC key: SHA256:nxJ168FpD/BD25sqDMQGv1ji6E11Fops01b0QUEOLxg
```
and the ec key never change.

I modified /root/.ssh/config file, but not work
```
HostKeyAlgorithms ssh-rsa
```

### Actual behavior

use "ec key" connect remote

### Expected behavior

force use "rsa key" connect remote

**Comment by chenss-1** [comment]
I got a exception when not use root  and this EC key log  :

org.apache.sshd.common.SshException: No more authentication methods available.
How Can fix this ?

**Comment by tomaswolf** [comment]
If you're trying to configure an OpenSSH server: its config file is normally `/etc/ssh/sshd_config`.

If it's an Apache MINA sshd server, set it in whatever config file it reads, if any, or configure it in the code via `SshServer.setKeyPairProvider()`.

If you're trying to configure an Apache MINA sshd client: first, make sure that it does read the file and does something with the HostKeyAlgorithms setting. (I don't think it does.) In Java code, you could create your own `ClientSessionImpl` subclass and override `resolveAvailableSignaturesProposal()` to return the algorithms you want.

BTW, I would recommend to set at least `rsa-sha2-512,rsa-sha2-256,ssh-rsa`. "ssh-rsa" is deprecated because it uses the cryptographically unsafe SHA1 hash. (RSA keys are fine, just this key exchange algorithm isn't.)
