### ISSUE TITLE
Can mina sshd be used in Android?

### ISSUE THREAD

**Issue by dllhxll** [apache/mina-sshd#322]
### Version

2.9.2

### Bug description

I try to used mina sshd in Android but I have some problems:
1.  in LazyDefaultUserHomeFolderHolder, the path is read from System.getProperty("user.home"). But in Android, System.getProperty("user.home") is null. Will this be a problem?
2.  in ExceptionUtils, sshd uses class javax.management.MBeanException and javax.management.ReflectionException. But they don't exist on Android.

Can mina sshd be used in Android? Or is there any android version of sshd can be used in Android?

### Actual behavior

1. I change System.getProperty("user.home") to Environment.getExternalStorageDirectory().getAbsolutePath().  Otherwise, sshd can not connect to server.

### Expected behavior

sshd can run in android

**Comment by albertvaka** [comment]
Hey, just FYI we do use mina-sshd in Android in the KDE Connect project 🙂 

We just updated from v0.14.0 (from 10 years ago) to v2.13.1 😄

We haven't seen an issue with the Exceptions (yet?), but we did have to add a [workaround](https://invent.kde.org/network/kdeconnect-android/-/blob/90dbdee282e77e00fa88bc13fb1fc2cd6751b1ed/src/org/kde/kdeconnect/Plugins/SftpPlugin/SimpleSftpServer.kt#L213) to not use the `user.home` property.

**Comment by albertvaka** [comment]
Hey, just FYI we do use mina-sshd in Android in the KDE Connect project 🙂 

We just updated from v0.14.0 (from 10 years ago) to v2.13.1 😄

We haven't seen an issue with the Exceptions (yet?), but we did have to add a [workaround](https://invent.kde.org/network/kdeconnect-android/-/blob/90dbdee282e77e00fa88bc13fb1fc2cd6751b1ed/src/org/kde/kdeconnect/Plugins/SftpPlugin/SimpleSftpServer.kt#L213) to not use the `user.home` property.

Other than that, Mina SSHD runs quite well on Android. Since Android 11 (API version  30) it can run unmodified. On older versions it's not possible to use the `NativeFileSystemFactory` because to access the filesystem you have to use the Storage Access Framework API, so we had to implement our own `FileSystemFactory ` using that, and we even went further and added more compatibility hacks to support down to Android 5.0, but you probably don't want to go that far.

**Comment by albertvaka** [comment]
The code is open source (GPL2 & GPL3) and can be found in https://invent.kde.org/network/kdeconnect-android/-/tree/master/src/org/kde/kdeconnect/Plugins/SftpPlugin

**Comment by tomaswolf** [comment]
Probably you all are aware of this already and I'm making a fool of myself by stating the obvious :-) : the GPL (any version) is incompatible with the APL.

**Comment by albertvaka** [comment]
We could honestly re-license this portion of code if you guys really want it, but we had to make so many hacks to make it work in older Android versions that I honestly think you are better off supporting only Android 11+ (which only needs the home directory to be [overridden](https://invent.kde.org/network/kdeconnect-android/-/blob/90dbdee282e77e00fa88bc13fb1fc2cd6751b1ed/src/org/kde/kdeconnect/Plugins/SftpPlugin/SimpleSftpServer.kt#L213) to work out of the box).

**Comment by ShellWen** [comment]
I did some work on #580
