### ISSUE TITLE
Can not start the server again

### ISSUE THREAD

**Issue by yanliangchao** [apache/mina-sshd#339]
### Description

SshServer server = SshServer.setUpDefaultServer();
......
server.start();
.....
server.stop();
......
server.start();

### Motivation

I want to start the SSH server again after stopping, but I can't.

**Comment by tomaswolf** [comment]
> I want to start the SSH server again after stopping, but I can't.

Why not?

**Comment by yanliangchao** [comment]
When I execute the start method in SshServer, he will first use the isClosed method to make a judgment.
![image](https://user-images.githubusercontent.com/32755174/226528857-6df484fa-b944-4f66-b185-f91465ee5ca5.png)
However, after I execute the stop method, the State will be changed to Closed, which will cause me to fail to execute the next step through this judgment after executing the start method again.
![image](https://user-images.githubusercontent.com/32755174/226528856-83beab8d-47f9-4d13-b6cb-fd97d258f67d.png)
How do I change the value of state.

**Comment by tomaswolf** [comment]
Not being able to re-start a closed client or server is basically due to many components in Apache MINA sshd having state machines that end in a "closed" terminal state. These state machines typically have no transition back to the initial state, and any attempt to implement such a transition would only complicate the code *a lot*. I'm not even sure it'd be always possible. It also does not fit with the lifecycle of SSH protocol objects such a sessions or channels. Once a channel is closed, it cannot be re-opened (but a new channel can be opened).

Hence using a `ServerBuilder` or `ClientBuilder` and creating a new server or client instance is the way to go. I'll close this issue as "won't fix".
