### ISSUE TITLE
Handling Encryption and TCP Handshake Timing in TCP/IP Port Forwarding with Mina-sshd for SSH Proxy to Web Service

### ISSUE THREAD

**Issue by SPuerBRead** [apache/mina-sshd#379]
Hello, I have the following scenario and encountered some issues while using mina-sshd for TCP/IP Port Forwarding. I would like to learn if there is a solution available.

sshclient (192.168.1.1) -> ssh-jumper (10.10.1.2) -> sshserver (10.10.1.1) -> web service (10.10.1.1 listens on 127.0.0.1)

The ssh-jumper is a relay server used for forwarding SSH connections. Since the web service is listening on 127.0.0.1, I want to access the web service through SSH proxy.

The current issue is that when the sshserver (10.10.1.1) receives a request and forwards it to the web service, it times out (the web service has a 1-second timeout, from TCP handshake to sending data packets).

If it exceeds 1 second, the request fails. I am currently using mina-sshd for these operations, but I noticed that all requests are timing out. I would like to learn if there is a way to allow the sshserver to establish the TCP handshake with the web service after receiving and decrypting the request. The current mode seems to establish the handshake first and then perform decryption, which causes some timeouts.

**Comment by SPuerBRead** [comment]
My English skills are not very advanced, so I apologize for any limitations in my translation.

**Comment by tomaswolf** [comment]
Take a look at the diagrams at [TCP/IP Forwarding](https://github.com/apache/mina-sshd/blob/master/docs/technical/tcpip-forwarding.md): the TCP/IP connection between the ssh-server and the web service has to be established first, and then ssh-server can tell the client SSH_MSG_CHANNEL_OPEN_SUCCESS, and only then the client sends data.

To change this, we would have to allow the client to write data before it received SSH_MSG_CHANNEL_OPEN_SUCCESS, but that is impossible because the channel window size is announced only in that message.

So ssh-server would have to send that SSH_MSG_CHANNEL_OPEN_SUCCESS message early, claiming the channel was open when in fact it hasn't yet made the connection to the web service. Then, ssh-server would have to buffer data received from the client (up to that channel window, which therefore should not be too large yet). Once the connection to the web service is successful, it could then forward the buffered data, and once that buffer is forwarded, possibly increase the channel window size. If the connection to the web service fails, ssh-server would have to close the channel like on any other connection failure.

Sounds not impossible, but is a lot of work.

**Comment by SPuerBRead** [comment]
Thanks for the answer. I pretty much understand it now. I'll take a look and see if I can implement it.
